ALTER TYPE "TemplateCategory" ADD VALUE IF NOT EXISTS 'EDUCATION' BEFORE 'CUSTOM';
ALTER TYPE "TemplateCategory" ADD VALUE IF NOT EXISTS 'BUSINESS' BEFORE 'CUSTOM';
ALTER TYPE "TemplateCategory" ADD VALUE IF NOT EXISTS 'SELF_HELP' BEFORE 'CUSTOM';
ALTER TYPE "TemplateCategory" ADD VALUE IF NOT EXISTS 'HEALTH' BEFORE 'CUSTOM';
ALTER TYPE "TemplateCategory" ADD VALUE IF NOT EXISTS 'BIOGRAPHY' BEFORE 'CUSTOM';
ALTER TYPE "TemplateCategory" ADD VALUE IF NOT EXISTS 'HISTORY' BEFORE 'CUSTOM';
ALTER TYPE "TemplateCategory" ADD VALUE IF NOT EXISTS 'SOCIETY' BEFORE 'CUSTOM';
ALTER TYPE "TemplateCategory" ADD VALUE IF NOT EXISTS 'ARTS' BEFORE 'CUSTOM';
